name: credit_default
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.2.4
  - numpy=1.21.2
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - pandas=1.1.5
  - pip:
    - inference-schema[numpy-support]==1.3.0
    - xlrd==2.0.1
    - mlflow==2.10.0
    - azureml-mlflow==1.48.0
    - seaborn==0.12.2